/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view;

import controller.ControllerVenderCripto;
import model.Investidor;

/**
 *
 * @author eric song
 */
public class JanelaVenderCripto extends javax.swing.JFrame {
    private Investidor investidor;
    /**
     * Creates new form JanelaComprarCripto
     */
    public JanelaVenderCripto(Investidor investidor) {
        initComponents();
        controller = new ControllerVenderCripto(this, investidor);
        this.investidor = investidor;
        
        double cotacaoBitcoin = investidor.getCarteira().getMoedas().get(1).getCotacao();
        String cotacaoBitcoinFormatada = String.format("%.2f", cotacaoBitcoin);
        cotacaoBitcoinLbl.setText(cotacaoBitcoinFormatada);
        double cotacaoEthereum = investidor.getCarteira().getMoedas().get(2).getCotacao();
        String cotacaoEthereumFormatada = String.format("%.2f", cotacaoEthereum);
        cotacaoEthereumLbl.setText(cotacaoEthereumFormatada);
        double cotacaoRipple = investidor.getCarteira().getMoedas().get(3).getCotacao();
        String cotacaoRippleFormatada = String.format("%.2f", cotacaoRipple);
        cotacaoRippleLbl.setText(cotacaoRippleFormatada);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        cotacoesLbl = new javax.swing.JLabel();
        bitcoinLbl = new javax.swing.JLabel();
        ethereumLbl = new javax.swing.JLabel();
        rippleLbl = new javax.swing.JLabel();
        cotacaoBitcoinLbl = new javax.swing.JLabel();
        cotacaoEthereumLbl = new javax.swing.JLabel();
        cotacaoRippleLbl = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        venderBitcoinBtn = new javax.swing.JButton();
        venderEthereumBtn = new javax.swing.JButton();
        venderRippleBtn = new javax.swing.JButton();
        voltarBtn = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        cotacoesLbl.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        cotacoesLbl.setText("COTAÇÕES:");

        bitcoinLbl.setFont(new java.awt.Font("Segoe UI", 0, 15)); // NOI18N
        bitcoinLbl.setText("Bitcoin:");

        ethereumLbl.setFont(new java.awt.Font("Segoe UI", 0, 15)); // NOI18N
        ethereumLbl.setText("Ethereum:");

        rippleLbl.setFont(new java.awt.Font("Segoe UI", 0, 15)); // NOI18N
        rippleLbl.setText("Ripple:");

        cotacaoBitcoinLbl.setFont(new java.awt.Font("Segoe UI", 0, 15)); // NOI18N
        cotacaoBitcoinLbl.setText("COT_BIT");

        cotacaoEthereumLbl.setFont(new java.awt.Font("Segoe UI", 0, 15)); // NOI18N
        cotacaoEthereumLbl.setText("COT_ETH");

        cotacaoRippleLbl.setFont(new java.awt.Font("Segoe UI", 0, 15)); // NOI18N
        cotacaoRippleLbl.setText("COT_RIP");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(cotacoesLbl))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(29, 29, 29)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(cotacaoBitcoinLbl)
                            .addComponent(bitcoinLbl))))
                .addGap(97, 97, 97)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(cotacaoEthereumLbl)
                    .addComponent(ethereumLbl))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 124, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(rippleLbl)
                    .addComponent(cotacaoRippleLbl))
                .addGap(40, 40, 40))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(cotacoesLbl)
                .addGap(40, 40, 40)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(bitcoinLbl)
                    .addComponent(ethereumLbl)
                    .addComponent(rippleLbl))
                .addGap(34, 34, 34)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cotacaoBitcoinLbl)
                    .addComponent(cotacaoEthereumLbl)
                    .addComponent(cotacaoRippleLbl))
                .addContainerGap(40, Short.MAX_VALUE))
        );

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel1.setText("VENDER CRIPTOMOEDA");

        venderBitcoinBtn.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        venderBitcoinBtn.setText("VENDER BITCOIN");
        venderBitcoinBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                venderBitcoinBtnActionPerformed(evt);
            }
        });

        venderEthereumBtn.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        venderEthereumBtn.setText("VENDER ETHEREUM");
        venderEthereumBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                venderEthereumBtnActionPerformed(evt);
            }
        });

        venderRippleBtn.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        venderRippleBtn.setText("VENDER RIPPLE");
        venderRippleBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                venderRippleBtnActionPerformed(evt);
            }
        });

        voltarBtn.setText("VOLTAR");
        voltarBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                voltarBtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(168, 168, 168)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(venderBitcoinBtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(venderEthereumBtn, javax.swing.GroupLayout.DEFAULT_SIZE, 212, Short.MAX_VALUE)
                            .addComponent(venderRippleBtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(224, 224, 224)
                        .addComponent(voltarBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(35, 35, 35)
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(139, 139, 139)
                        .addComponent(jLabel1)))
                .addContainerGap(37, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(39, 39, 39)
                .addComponent(jLabel1)
                .addGap(40, 40, 40)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(venderBitcoinBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(27, 27, 27)
                .addComponent(venderEthereumBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(32, 32, 32)
                .addComponent(venderRippleBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 30, Short.MAX_VALUE)
                .addComponent(voltarBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void voltarBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_voltarBtnActionPerformed
        this.setVisible(false);
    }//GEN-LAST:event_voltarBtnActionPerformed

    private void venderBitcoinBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_venderBitcoinBtnActionPerformed
        JanelaVenderBitcoin cb = new JanelaVenderBitcoin(investidor);
        cb.setVisible(true);
    }//GEN-LAST:event_venderBitcoinBtnActionPerformed

    private void venderEthereumBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_venderEthereumBtnActionPerformed
        JanelaVenderEthereum ce = new JanelaVenderEthereum(investidor);
        ce.setVisible(true);
    }//GEN-LAST:event_venderEthereumBtnActionPerformed

    private void venderRippleBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_venderRippleBtnActionPerformed
        JanelaVenderRipple ce = new JanelaVenderRipple(investidor);
        ce.setVisible(true);
    }//GEN-LAST:event_venderRippleBtnActionPerformed

    /**
     * @param args the command line arguments
     */
//    public static void main(String args[]) {
//        /* Set the Nimbus look and feel */
//        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
//        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
//         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
//         */
//        try {
//            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
//                if ("Nimbus".equals(info.getName())) {
//                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
//                    break;
//                }
//            }
//        } catch (ClassNotFoundException ex) {
//            java.util.logging.Logger.getLogger(JanelaComprarCripto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (InstantiationException ex) {
//            java.util.logging.Logger.getLogger(JanelaComprarCripto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (IllegalAccessException ex) {
//            java.util.logging.Logger.getLogger(JanelaComprarCripto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
//            java.util.logging.Logger.getLogger(JanelaComprarCripto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        }
//        //</editor-fold>
//
//        /* Create and display the form */
//        java.awt.EventQueue.invokeLater(new Runnable() {
//            public void run() {
//                new JanelaComprarCripto().setVisible(true);
//            }
//        });
//    }
    
    private ControllerVenderCripto controller;
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel bitcoinLbl;
    private javax.swing.JLabel cotacaoBitcoinLbl;
    private javax.swing.JLabel cotacaoEthereumLbl;
    private javax.swing.JLabel cotacaoRippleLbl;
    private javax.swing.JLabel cotacoesLbl;
    private javax.swing.JLabel ethereumLbl;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel rippleLbl;
    private javax.swing.JButton venderBitcoinBtn;
    private javax.swing.JButton venderEthereumBtn;
    private javax.swing.JButton venderRippleBtn;
    private javax.swing.JButton voltarBtn;
    // End of variables declaration//GEN-END:variables
}
